services:
  # Backend: Dockerized Web Service
  - type: web
    name: texforge-backend
    env: docker
    rootDir: backend
    healthCheckPath: /health
    autoDeploy: true

  # Frontend: Static Site
  - type: web
    name: texforge-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        # Correctly construct the URL from the 'host' property
        value: https://${texforge-backend.host}