services:
  # Backend: Dockerized Web Service
  - type: web
    name: texforge-backend
    env: docker
    rootDir: backend
    healthCheckPath: /health
    autoDeploy: true

  # Frontend: Static Site
  - type: static
    name: texforge-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: texforge-backend
          property: url